version: "2"

linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - goconst
    - revive
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unused
  settings:
    dogsled:
      max-blank-identifiers: 3
      suggest-new: true

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-same-issues: 50
