-- +migrate Up
CREATE TABLE URL_MAPPING
(
    ORIGINAL_URL TEXT NOT NULL,
    SHORTENED_URL TEXT NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS URL_MAPPING_INDEX ON URL_MAPPING(ORIGINAL_URL, SHORTENED_URL);
-- +migrate Down
